# Generated by Django 5.2.8 on 2025-11-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_barangay_client_contact_no_client_livelihood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('SEA', 'SEA'), ('AICS', 'AICS'), ('REDCARD', 'REDCARD')], max_length=20)),
                ('barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('livelihood', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='core.client')),
            ],
        ),
    ]
