# Generated by Django 5.2.8 on 2025-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicationdocument_description_assistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.CharField(choices=[('SEA', 'SEA'), ('AICS', 'AICS'), ('REDCARD', 'REDCARD'), ('EA', 'Educational Assistance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='program',
            field=models.CharField(choices=[('SEA', 'SEA'), ('AICS', 'AICS'), ('REDCARD', 'REDCARD'), ('EA', 'Educational Assistance')], max_length=20),
        ),
    ]
