# Generated by Django 5.2.10 on 2026-01-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_program_application_aid_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assessed', 'Assessed'), ('pending', 'For Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('released', 'Released')], default='pending', max_length=30),
        ),
    ]
