# Generated by Django 5.2.10 on 2026-01-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('referral', 'Referrals'), ('other', 'Others'), ('organic', 'Organic Search')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='AICSDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crisis_type', models.CharField(choices=[('Medical', 'Medical'), ('Burial', 'Burial'), ('Transportation', 'Transportation'), ('Educational', 'Educational')], max_length=50)),
                ('assessment_findings', models.TextField()),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aics_detail', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalAssistanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('course_or_grade', models.CharField(max_length=255)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educational_detail', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='REDCARDDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('allowable_limit', models.PositiveIntegerField(default=3)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redcard_detail', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='SEADetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=255)),
                ('capital_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('training_completed', models.BooleanField(default=False)),
                ('monitoring_notes', models.TextField(blank=True, null=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sea_detail', to='core.application')),
            ],
        ),
    ]
