# Generated by Django 5.2.10 on 2026-02-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_application_approved_amount_application_assessed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fourps_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_4ps',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed')], max_length=1, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('educational_attainment', models.CharField(blank=True, choices=[('Elem', 'Elementary'), ('HS', 'High School'), ('Coll/Voc', 'College / Vocational'), ('Illit', 'Illiterate')], max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='core.client')),
            ],
        ),
    ]