# Generated by Django 5.2.10 on 2026-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clientaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='document_name',
            field=models.CharField(default='Unknown Document', max_length=150),
            preserve_default=False,
        ),
    ]
