# Generated by Django 5.2.10 on 2026-02-05 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_applicationdocument_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='aid_type',
            field=models.CharField(choices=[('AICS', 'AICS'), ('SEA', 'Sustainable Livelihood (SEA)'), ('REDCARD', 'Red Card'), ('EDUCATIONAL', 'Educational Assistance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ASSESSMENT', 'Under Assessment'), ('APPROVAL', 'For Approval'), ('RELEASE', 'For Release'), ('RELEASED', 'Released'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
