# Generated by Django 5.2.10 on 2026-02-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_application_phone_number'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='application',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='application',
            name='requested_amount',
        ),
        migrations.RemoveField(
            model_name='seadetail',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='seadetail',
            name='capital_requested',
        ),
        migrations.RemoveField(
            model_name='seadetail',
            name='monitoring_notes',
        ),
        migrations.RemoveField(
            model_name='seadetail',
            name='training_completed',
        ),
    ]
