# Generated by Django 5.2.10 on 2026-02-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [
     
    ]
