# Generated by Django 5.2.10 on 2026-02-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_application_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicsdetail',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='applicationdocument',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='seadetail',
            name='released_at',
        ),
        migrations.AlterField(
            model_name='aicsdetail',
            name='crisis_type',
            field=models.CharField(blank=True, choices=[('Medical', 'Medical'), ('Death', 'Death'), ('Fire Victim', 'Fire Victim'), ('Calamity', 'Calamity'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='educationalassistancedetail',
            name='course_or_grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationalassistancedetail',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redcarddetail',
            name='emergency_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
