# Generated by Django 5.2.10 on 2026-02-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [
    ]
