# Generated by Django 5.2.10 on 2026-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_aicsdetail_approved_amount_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('Social Protection & Development Report (SPDR)', 'Social Protection & Development Report (SPDR)'), ('Local Council for the Protection of Children (LCPC) Report', 'Local Council for the Protection of Children (LCPC) Report'), ('Local Council Against Trafficking & Violence Against Women & their Children (LCAT VAWC) Report', 'Local Council Against Trafficking & VAWC Report'), ('Other Reports', 'Other Reports')], max_length=200, null=True),
        ),
    ]
