# Generated by Django 5.2.10 on 2026-03-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [

    ]
