# Generated by Django 5.2.10 on 2026-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_aicsdetail_approved_amount'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='client',
            name='is_indigenous',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_solo_parent',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
    ]
