# Generated by Django 5.2.10 on 2026-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='application',
            name='eligibility_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
