# Generated by Django 5.2.10 on 2026-03-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [
      
    ]
