# Generated by Django 5.2.10 on 2026-04-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_aicsdetail_approved_amount'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='application',
            name='eligibility_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='familymember',
            name='sectors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
