# Generated by Django 5.2.10 on 2026-04-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [
 
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('Social Protection & Development Report (SPDR)', 'Social Protection & Development Report (SPDR)'), ('Local Council for the Protection of Children (LCPC) Report', 'Local Council for the Protection of Children (LCPC) Report'), ('Local Council Against Trafficking & Violence Against Women & their Children (LCAT VAWC) Report', 'Local Council Against Trafficking & VAWC Report'), ('Persons with Disability Report (PWD)', 'Persons with Disability Report (PWD)'), ('Report of the Office of Senior Citizen Affairs (OSCA)', 'Report of the Office of Senior Citizen Affairs (OSCA)'), ('CICL / CAR Report', 'CICL / CAR Report'), ('CNSP Report', 'CNSP Report'), ('Migrant Workers Report', 'Migrant Workers Report'), ('Indigenous People Progress Updates (IP)', 'Indigenous People Progress Updates (IP)'), ('Report on Former Rebels (FR)', 'Report on Former Rebels (FR)'), ('Persons Who Use Drugs Report (PWUD)', 'Persons Who Use Drugs Report (PWUD)'), ('Other Reports', 'Other Reports')], max_length=200, null=True),
        ),
    ]
