# Generated by Django 5.2.10 on 2026-04-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [
  
    ]
