# Generated by Django 5.2.10 on 2026-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_aicsdetail_approved_amount'),
    ]

    operations = [
   
        migrations.AddField(
            model_name='clientaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
