# Generated by Django 5.2.10 on 2026-05-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='clientaccount',
            name='verification_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
