# Generated by Django 5.2.10 on 2026-09-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_aicsdetail_approved_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicsdetail',
            name='approved_amount',
        ),
        migrations.RemoveField(
            model_name='aicsdetail',
            name='assessment_findings',
        ),
    ]
